fragment AgendaParts on Agenda {
  __typename
  titre
  categorie
  date
  date_fin
  rythme
  heure
  lieu
  prix
  earlybird
  cta
  site
  lien
  resume
  image
  reservable
  ordre
  publie
  body
}

fragment OffresParts on Offres {
  __typename
  titre
  categorie
  tag
  resume
  prix
  duree
  format
  tarifs {
    __typename
    label
    prix
    detail
  }
  image
  lien
  reservable
  ordre
  publie
  body
}

fragment PagesParts on Pages {
  __typename
  hero_eyebrow
  hero_titre
  hero_accent
  hero_paragraphe
  hero_cta
  piliers_titre
  citation1
  propositions_titre
  propositions {
    __typename
    titre
    texte
    cta
  }
  citation2
  citation_contact
  form_titre
  form_intro
}

fragment Page_aproposParts on Page_apropos {
  __typename
  hero_eyebrow
  hero_titre
  chapitres {
    __typename
    titre
    texte
  }
}

fragment Page_soinsParts on Page_soins {
  __typename
  hero_eyebrow
  hero_titre
  coeur
  soins_eyebrow
  soins_titre
  soins_intro
}

fragment Page_accompagnementParts on Page_accompagnement {
  __typename
  hero_eyebrow
  hero_titre
  hero_image
  coeur
  pourqui_eyebrow
  pourqui_titre
  pourqui_texte
  outils_eyebrow
  outils_titre
  outils
  passage
  formules_eyebrow
  formules_titre
}

fragment Page_quintessenceParts on Page_quintessence {
  __typename
  hero_eyebrow
  hero_titre
  hero_lead
  hero_image
  passage
  citation
  silence_titre
  silence_texte
  crea_titre
  crea_texte
  pratiques_eyebrow
  pratiques_titre
  pratiques
  cta_texte
}

fragment Page_contactParts on Page_contact {
  __typename
  hero_eyebrow
  hero_titre
  hero_image
  intro
}
