//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  agenda: Agenda;
  agendaConnection: AgendaConnection;
  offres: Offres;
  offresConnection: OffresConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAgendaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAgendaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AgendaFilter>;
};


export type QueryOffresArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOffresConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OffresFilter>;
};

export type DocumentFilter = {
  agenda?: InputMaybe<AgendaFilter>;
  offres?: InputMaybe<OffresFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Agenda | Offres | Folder;

export type Agenda = Node & Document & {
  __typename?: 'Agenda';
  titre: Scalars['String']['output'];
  categorie: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  date_fin?: Maybe<Scalars['String']['output']>;
  rythme?: Maybe<Scalars['String']['output']>;
  heure?: Maybe<Scalars['String']['output']>;
  lieu?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  earlybird?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
  site?: Maybe<Scalars['String']['output']>;
  lien?: Maybe<Scalars['String']['output']>;
  resume?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  reservable?: Maybe<Scalars['Boolean']['output']>;
  ordre?: Maybe<Scalars['Float']['output']>;
  publie?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AgendaFilter = {
  titre?: InputMaybe<StringFilter>;
  categorie?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  date_fin?: InputMaybe<DatetimeFilter>;
  rythme?: InputMaybe<StringFilter>;
  heure?: InputMaybe<StringFilter>;
  lieu?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  earlybird?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  site?: InputMaybe<StringFilter>;
  lien?: InputMaybe<StringFilter>;
  resume?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  reservable?: InputMaybe<BooleanFilter>;
  ordre?: InputMaybe<NumberFilter>;
  publie?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AgendaConnectionEdges = {
  __typename?: 'AgendaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Agenda>;
};

export type AgendaConnection = Connection & {
  __typename?: 'AgendaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AgendaConnectionEdges>>>;
};

export type OffresTarifs = {
  __typename?: 'OffresTarifs';
  label?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  detail?: Maybe<Scalars['String']['output']>;
};

export type Offres = Node & Document & {
  __typename?: 'Offres';
  titre: Scalars['String']['output'];
  categorie: Scalars['String']['output'];
  tag?: Maybe<Scalars['String']['output']>;
  resume?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  duree?: Maybe<Scalars['String']['output']>;
  format?: Maybe<Scalars['String']['output']>;
  tarifs?: Maybe<Array<Maybe<OffresTarifs>>>;
  image?: Maybe<Scalars['String']['output']>;
  lien?: Maybe<Scalars['String']['output']>;
  reservable?: Maybe<Scalars['Boolean']['output']>;
  ordre?: Maybe<Scalars['Float']['output']>;
  publie?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OffresTarifsFilter = {
  label?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  detail?: InputMaybe<StringFilter>;
};

export type OffresFilter = {
  titre?: InputMaybe<StringFilter>;
  categorie?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  resume?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  duree?: InputMaybe<StringFilter>;
  format?: InputMaybe<StringFilter>;
  tarifs?: InputMaybe<OffresTarifsFilter>;
  image?: InputMaybe<ImageFilter>;
  lien?: InputMaybe<StringFilter>;
  reservable?: InputMaybe<BooleanFilter>;
  ordre?: InputMaybe<NumberFilter>;
  publie?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type OffresConnectionEdges = {
  __typename?: 'OffresConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Offres>;
};

export type OffresConnection = Connection & {
  __typename?: 'OffresConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OffresConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAgenda: Agenda;
  createAgenda: Agenda;
  updateOffres: Offres;
  createOffres: Offres;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAgendaArgs = {
  relativePath: Scalars['String']['input'];
  params: AgendaMutation;
};


export type MutationCreateAgendaArgs = {
  relativePath: Scalars['String']['input'];
  params: AgendaMutation;
};


export type MutationUpdateOffresArgs = {
  relativePath: Scalars['String']['input'];
  params: OffresMutation;
};


export type MutationCreateOffresArgs = {
  relativePath: Scalars['String']['input'];
  params: OffresMutation;
};

export type DocumentUpdateMutation = {
  agenda?: InputMaybe<AgendaMutation>;
  offres?: InputMaybe<OffresMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  agenda?: InputMaybe<AgendaMutation>;
  offres?: InputMaybe<OffresMutation>;
};

export type AgendaMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  categorie?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  date_fin?: InputMaybe<Scalars['String']['input']>;
  rythme?: InputMaybe<Scalars['String']['input']>;
  heure?: InputMaybe<Scalars['String']['input']>;
  lieu?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  earlybird?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
  site?: InputMaybe<Scalars['String']['input']>;
  lien?: InputMaybe<Scalars['String']['input']>;
  resume?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  reservable?: InputMaybe<Scalars['Boolean']['input']>;
  ordre?: InputMaybe<Scalars['Float']['input']>;
  publie?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type OffresTarifsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  detail?: InputMaybe<Scalars['String']['input']>;
};

export type OffresMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  categorie?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  resume?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  duree?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  tarifs?: InputMaybe<Array<InputMaybe<OffresTarifsMutation>>>;
  image?: InputMaybe<Scalars['String']['input']>;
  lien?: InputMaybe<Scalars['String']['input']>;
  reservable?: InputMaybe<Scalars['Boolean']['input']>;
  ordre?: InputMaybe<Scalars['Float']['input']>;
  publie?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type AgendaFilter = {
  titre?: StringFilter | null | undefined;
  categorie?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  date_fin?: DatetimeFilter | null | undefined;
  rythme?: StringFilter | null | undefined;
  heure?: StringFilter | null | undefined;
  lieu?: StringFilter | null | undefined;
  prix?: StringFilter | null | undefined;
  earlybird?: StringFilter | null | undefined;
  cta?: StringFilter | null | undefined;
  site?: StringFilter | null | undefined;
  lien?: StringFilter | null | undefined;
  resume?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  reservable?: BooleanFilter | null | undefined;
  ordre?: NumberFilter | null | undefined;
  publie?: BooleanFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type OffresTarifsFilter = {
  label?: StringFilter | null | undefined;
  prix?: StringFilter | null | undefined;
  detail?: StringFilter | null | undefined;
};

export type OffresFilter = {
  titre?: StringFilter | null | undefined;
  categorie?: StringFilter | null | undefined;
  tag?: StringFilter | null | undefined;
  resume?: StringFilter | null | undefined;
  prix?: StringFilter | null | undefined;
  duree?: StringFilter | null | undefined;
  format?: StringFilter | null | undefined;
  tarifs?: OffresTarifsFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  lien?: StringFilter | null | undefined;
  reservable?: BooleanFilter | null | undefined;
  ordre?: NumberFilter | null | undefined;
  publie?: BooleanFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type AgendaPartsFragment = { __typename: 'Agenda', titre: string, categorie: string, date: string | null, date_fin: string | null, rythme: string | null, heure: string | null, lieu: string | null, prix: string | null, earlybird: string | null, cta: string | null, site: string | null, lien: string | null, resume: string | null, image: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null };

export type OffresPartsFragment = { __typename: 'Offres', titre: string, categorie: string, tag: string | null, resume: string | null, prix: string | null, duree: string | null, format: string | null, image: string | null, lien: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, tarifs: Array<{ __typename: 'OffresTarifs', label: string | null, prix: string | null, detail: string | null } | null> | null };

export type AgendaQueryVariables = Exact<{
  relativePath: string;
}>;


export type AgendaQuery = { agenda: { __typename: 'Agenda', id: string, titre: string, categorie: string, date: string | null, date_fin: string | null, rythme: string | null, heure: string | null, lieu: string | null, prix: string | null, earlybird: string | null, cta: string | null, site: string | null, lien: string | null, resume: string | null, image: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AgendaConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: AgendaFilter | null | undefined;
}>;


export type AgendaConnectionQuery = { agendaConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Agenda', id: string, titre: string, categorie: string, date: string | null, date_fin: string | null, rythme: string | null, heure: string | null, lieu: string | null, prix: string | null, earlybird: string | null, cta: string | null, site: string | null, lien: string | null, resume: string | null, image: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type OffresQueryVariables = Exact<{
  relativePath: string;
}>;


export type OffresQuery = { offres: { __typename: 'Offres', id: string, titre: string, categorie: string, tag: string | null, resume: string | null, prix: string | null, duree: string | null, format: string | null, image: string | null, lien: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, tarifs: Array<{ __typename: 'OffresTarifs', label: string | null, prix: string | null, detail: string | null } | null> | null } };

export type OffresConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: OffresFilter | null | undefined;
}>;


export type OffresConnectionQuery = { offresConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Offres', id: string, titre: string, categorie: string, tag: string | null, resume: string | null, prix: string | null, duree: string | null, format: string | null, image: string | null, lien: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, tarifs: Array<{ __typename: 'OffresTarifs', label: string | null, prix: string | null, detail: string | null } | null> | null } | null } | null> | null } };

export const AgendaPartsFragmentDoc = gql`
    fragment AgendaParts on Agenda {
  __typename
  titre
  categorie
  date
  date_fin
  rythme
  heure
  lieu
  prix
  earlybird
  cta
  site
  lien
  resume
  image
  reservable
  ordre
  publie
  body
}
    `;
export const OffresPartsFragmentDoc = gql`
    fragment OffresParts on Offres {
  __typename
  titre
  categorie
  tag
  resume
  prix
  duree
  format
  tarifs {
    __typename
    label
    prix
    detail
  }
  image
  lien
  reservable
  ordre
  publie
  body
}
    `;
export const AgendaDocument = gql`
    query agenda($relativePath: String!) {
  agenda(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AgendaParts
  }
}
    ${AgendaPartsFragmentDoc}`;
export const AgendaConnectionDocument = gql`
    query agendaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AgendaFilter) {
  agendaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AgendaParts
      }
    }
  }
}
    ${AgendaPartsFragmentDoc}`;
export const OffresDocument = gql`
    query offres($relativePath: String!) {
  offres(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OffresParts
  }
}
    ${OffresPartsFragmentDoc}`;
export const OffresConnectionDocument = gql`
    query offresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OffresFilter) {
  offresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OffresParts
      }
    }
  }
}
    ${OffresPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      agenda(variables: AgendaQueryVariables, options?: C): Promise<{data: AgendaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaQueryVariables, query: string}> {
        return requester<{data: AgendaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaQueryVariables, query: string}, AgendaQueryVariables>(AgendaDocument, variables, options);
      },
    agendaConnection(variables?: AgendaConnectionQueryVariables, options?: C): Promise<{data: AgendaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaConnectionQueryVariables, query: string}> {
        return requester<{data: AgendaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaConnectionQueryVariables, query: string}, AgendaConnectionQueryVariables>(AgendaConnectionDocument, variables, options);
      },
    offres(variables: OffresQueryVariables, options?: C): Promise<{data: OffresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresQueryVariables, query: string}> {
        return requester<{data: OffresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresQueryVariables, query: string}, OffresQueryVariables>(OffresDocument, variables, options);
      },
    offresConnection(variables?: OffresConnectionQueryVariables, options?: C): Promise<{data: OffresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresConnectionQueryVariables, query: string}> {
        return requester<{data: OffresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresConnectionQueryVariables, query: string}, OffresConnectionQueryVariables>(OffresConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/3.0/content/ac005920-bdf5-45df-a7d6-5d99cc50423a/github/tina",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  