//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  agenda: Agenda;
  agendaConnection: AgendaConnection;
  offres: Offres;
  offresConnection: OffresConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
  page_apropos: Page_Apropos;
  page_aproposConnection: Page_AproposConnection;
  page_soins: Page_Soins;
  page_soinsConnection: Page_SoinsConnection;
  page_accompagnement: Page_Accompagnement;
  page_accompagnementConnection: Page_AccompagnementConnection;
  page_quintessence: Page_Quintessence;
  page_quintessenceConnection: Page_QuintessenceConnection;
  page_contact: Page_Contact;
  page_contactConnection: Page_ContactConnection;
  images: Images;
  imagesConnection: ImagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAgendaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAgendaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AgendaFilter>;
};


export type QueryOffresArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOffresConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OffresFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryPage_AproposArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPage_AproposConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Page_AproposFilter>;
};


export type QueryPage_SoinsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPage_SoinsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Page_SoinsFilter>;
};


export type QueryPage_AccompagnementArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPage_AccompagnementConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Page_AccompagnementFilter>;
};


export type QueryPage_QuintessenceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPage_QuintessenceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Page_QuintessenceFilter>;
};


export type QueryPage_ContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPage_ContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Page_ContactFilter>;
};


export type QueryImagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryImagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ImagesFilter>;
};

export type DocumentFilter = {
  agenda?: InputMaybe<AgendaFilter>;
  offres?: InputMaybe<OffresFilter>;
  pages?: InputMaybe<PagesFilter>;
  page_apropos?: InputMaybe<Page_AproposFilter>;
  page_soins?: InputMaybe<Page_SoinsFilter>;
  page_accompagnement?: InputMaybe<Page_AccompagnementFilter>;
  page_quintessence?: InputMaybe<Page_QuintessenceFilter>;
  page_contact?: InputMaybe<Page_ContactFilter>;
  images?: InputMaybe<ImagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Agenda | Offres | Pages | Page_Apropos | Page_Soins | Page_Accompagnement | Page_Quintessence | Page_Contact | Images | Folder;

export type Agenda = Node & Document & {
  __typename?: 'Agenda';
  titre: Scalars['String']['output'];
  categorie: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  date_fin?: Maybe<Scalars['String']['output']>;
  rythme?: Maybe<Scalars['String']['output']>;
  heure?: Maybe<Scalars['String']['output']>;
  lieu?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  earlybird?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
  site?: Maybe<Scalars['String']['output']>;
  lien?: Maybe<Scalars['String']['output']>;
  resume?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  reservable?: Maybe<Scalars['Boolean']['output']>;
  ordre?: Maybe<Scalars['Float']['output']>;
  publie?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AgendaFilter = {
  titre?: InputMaybe<StringFilter>;
  categorie?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  date_fin?: InputMaybe<DatetimeFilter>;
  rythme?: InputMaybe<StringFilter>;
  heure?: InputMaybe<StringFilter>;
  lieu?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  earlybird?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  site?: InputMaybe<StringFilter>;
  lien?: InputMaybe<StringFilter>;
  resume?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  reservable?: InputMaybe<BooleanFilter>;
  ordre?: InputMaybe<NumberFilter>;
  publie?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AgendaConnectionEdges = {
  __typename?: 'AgendaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Agenda>;
};

export type AgendaConnection = Connection & {
  __typename?: 'AgendaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AgendaConnectionEdges>>>;
};

export type OffresTarifs = {
  __typename?: 'OffresTarifs';
  label?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  detail?: Maybe<Scalars['String']['output']>;
};

export type Offres = Node & Document & {
  __typename?: 'Offres';
  titre: Scalars['String']['output'];
  categorie: Scalars['String']['output'];
  tag?: Maybe<Scalars['String']['output']>;
  resume?: Maybe<Scalars['String']['output']>;
  prix?: Maybe<Scalars['String']['output']>;
  duree?: Maybe<Scalars['String']['output']>;
  format?: Maybe<Scalars['String']['output']>;
  tarifs?: Maybe<Array<Maybe<OffresTarifs>>>;
  image?: Maybe<Scalars['String']['output']>;
  lien?: Maybe<Scalars['String']['output']>;
  reservable?: Maybe<Scalars['Boolean']['output']>;
  ordre?: Maybe<Scalars['Float']['output']>;
  publie?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OffresTarifsFilter = {
  label?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  detail?: InputMaybe<StringFilter>;
};

export type OffresFilter = {
  titre?: InputMaybe<StringFilter>;
  categorie?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  resume?: InputMaybe<StringFilter>;
  prix?: InputMaybe<StringFilter>;
  duree?: InputMaybe<StringFilter>;
  format?: InputMaybe<StringFilter>;
  tarifs?: InputMaybe<OffresTarifsFilter>;
  image?: InputMaybe<ImageFilter>;
  lien?: InputMaybe<StringFilter>;
  reservable?: InputMaybe<BooleanFilter>;
  ordre?: InputMaybe<NumberFilter>;
  publie?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type OffresConnectionEdges = {
  __typename?: 'OffresConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Offres>;
};

export type OffresConnection = Connection & {
  __typename?: 'OffresConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OffresConnectionEdges>>>;
};

export type PagesPropositions = {
  __typename?: 'PagesPropositions';
  titre?: Maybe<Scalars['String']['output']>;
  texte?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  hero_accent?: Maybe<Scalars['String']['output']>;
  hero_paragraphe?: Maybe<Scalars['String']['output']>;
  hero_cta?: Maybe<Scalars['String']['output']>;
  piliers_titre?: Maybe<Scalars['String']['output']>;
  citation1?: Maybe<Scalars['String']['output']>;
  propositions_titre?: Maybe<Scalars['String']['output']>;
  propositions?: Maybe<Array<Maybe<PagesPropositions>>>;
  citation2?: Maybe<Scalars['String']['output']>;
  citation_contact?: Maybe<Scalars['String']['output']>;
  form_titre?: Maybe<Scalars['String']['output']>;
  form_intro?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesPropositionsFilter = {
  titre?: InputMaybe<StringFilter>;
  texte?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
};

export type PagesFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  hero_accent?: InputMaybe<StringFilter>;
  hero_paragraphe?: InputMaybe<StringFilter>;
  hero_cta?: InputMaybe<StringFilter>;
  piliers_titre?: InputMaybe<StringFilter>;
  citation1?: InputMaybe<StringFilter>;
  propositions_titre?: InputMaybe<StringFilter>;
  propositions?: InputMaybe<PagesPropositionsFilter>;
  citation2?: InputMaybe<StringFilter>;
  citation_contact?: InputMaybe<StringFilter>;
  form_titre?: InputMaybe<StringFilter>;
  form_intro?: InputMaybe<StringFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Page_AproposChapitres = {
  __typename?: 'Page_aproposChapitres';
  titre?: Maybe<Scalars['String']['output']>;
  texte?: Maybe<Scalars['String']['output']>;
};

export type Page_Apropos = Node & Document & {
  __typename?: 'Page_apropos';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  chapitres?: Maybe<Array<Maybe<Page_AproposChapitres>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Page_AproposChapitresFilter = {
  titre?: InputMaybe<StringFilter>;
  texte?: InputMaybe<StringFilter>;
};

export type Page_AproposFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  chapitres?: InputMaybe<Page_AproposChapitresFilter>;
};

export type Page_AproposConnectionEdges = {
  __typename?: 'Page_aproposConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page_Apropos>;
};

export type Page_AproposConnection = Connection & {
  __typename?: 'Page_aproposConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Page_AproposConnectionEdges>>>;
};

export type Page_Soins = Node & Document & {
  __typename?: 'Page_soins';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  coeur?: Maybe<Scalars['String']['output']>;
  soins_eyebrow?: Maybe<Scalars['String']['output']>;
  soins_titre?: Maybe<Scalars['String']['output']>;
  soins_intro?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Page_SoinsFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  coeur?: InputMaybe<StringFilter>;
  soins_eyebrow?: InputMaybe<StringFilter>;
  soins_titre?: InputMaybe<StringFilter>;
  soins_intro?: InputMaybe<StringFilter>;
};

export type Page_SoinsConnectionEdges = {
  __typename?: 'Page_soinsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page_Soins>;
};

export type Page_SoinsConnection = Connection & {
  __typename?: 'Page_soinsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Page_SoinsConnectionEdges>>>;
};

export type Page_Accompagnement = Node & Document & {
  __typename?: 'Page_accompagnement';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  coeur?: Maybe<Scalars['String']['output']>;
  pourqui_eyebrow?: Maybe<Scalars['String']['output']>;
  pourqui_titre?: Maybe<Scalars['String']['output']>;
  pourqui_texte?: Maybe<Scalars['String']['output']>;
  outils_eyebrow?: Maybe<Scalars['String']['output']>;
  outils_titre?: Maybe<Scalars['String']['output']>;
  outils?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  passage?: Maybe<Scalars['String']['output']>;
  formules_eyebrow?: Maybe<Scalars['String']['output']>;
  formules_titre?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Page_AccompagnementFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  coeur?: InputMaybe<StringFilter>;
  pourqui_eyebrow?: InputMaybe<StringFilter>;
  pourqui_titre?: InputMaybe<StringFilter>;
  pourqui_texte?: InputMaybe<StringFilter>;
  outils_eyebrow?: InputMaybe<StringFilter>;
  outils_titre?: InputMaybe<StringFilter>;
  outils?: InputMaybe<StringFilter>;
  passage?: InputMaybe<StringFilter>;
  formules_eyebrow?: InputMaybe<StringFilter>;
  formules_titre?: InputMaybe<StringFilter>;
};

export type Page_AccompagnementConnectionEdges = {
  __typename?: 'Page_accompagnementConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page_Accompagnement>;
};

export type Page_AccompagnementConnection = Connection & {
  __typename?: 'Page_accompagnementConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Page_AccompagnementConnectionEdges>>>;
};

export type Page_Quintessence = Node & Document & {
  __typename?: 'Page_quintessence';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  hero_lead?: Maybe<Scalars['String']['output']>;
  passage?: Maybe<Scalars['String']['output']>;
  citation?: Maybe<Scalars['String']['output']>;
  silence_titre?: Maybe<Scalars['String']['output']>;
  silence_texte?: Maybe<Scalars['String']['output']>;
  crea_titre?: Maybe<Scalars['String']['output']>;
  crea_texte?: Maybe<Scalars['String']['output']>;
  pratiques_eyebrow?: Maybe<Scalars['String']['output']>;
  pratiques_titre?: Maybe<Scalars['String']['output']>;
  pratiques?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  cta_texte?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Page_QuintessenceFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  hero_lead?: InputMaybe<StringFilter>;
  passage?: InputMaybe<StringFilter>;
  citation?: InputMaybe<StringFilter>;
  silence_titre?: InputMaybe<StringFilter>;
  silence_texte?: InputMaybe<StringFilter>;
  crea_titre?: InputMaybe<StringFilter>;
  crea_texte?: InputMaybe<StringFilter>;
  pratiques_eyebrow?: InputMaybe<StringFilter>;
  pratiques_titre?: InputMaybe<StringFilter>;
  pratiques?: InputMaybe<StringFilter>;
  cta_texte?: InputMaybe<StringFilter>;
};

export type Page_QuintessenceConnectionEdges = {
  __typename?: 'Page_quintessenceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page_Quintessence>;
};

export type Page_QuintessenceConnection = Connection & {
  __typename?: 'Page_quintessenceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Page_QuintessenceConnectionEdges>>>;
};

export type Page_Contact = Node & Document & {
  __typename?: 'Page_contact';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Page_ContactFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
};

export type Page_ContactConnectionEdges = {
  __typename?: 'Page_contactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page_Contact>;
};

export type Page_ContactConnection = Connection & {
  __typename?: 'Page_contactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Page_ContactConnectionEdges>>>;
};

export type Images = Node & Document & {
  __typename?: 'Images';
  hero_accueil?: Maybe<Scalars['String']['output']>;
  hero_soins?: Maybe<Scalars['String']['output']>;
  hero_accomp?: Maybe<Scalars['String']['output']>;
  hero_agenda?: Maybe<Scalars['String']['output']>;
  hero_apropos?: Maybe<Scalars['String']['output']>;
  hero_quintessence?: Maybe<Scalars['String']['output']>;
  hero_partenaires?: Maybe<Scalars['String']['output']>;
  hero_contact?: Maybe<Scalars['String']['output']>;
  accueil_portrait?: Maybe<Scalars['String']['output']>;
  accueil_ateliers?: Maybe<Scalars['String']['output']>;
  accueil_soins?: Maybe<Scalars['String']['output']>;
  accueil_accomp?: Maybe<Scalars['String']['output']>;
  accueil_immersions?: Maybe<Scalars['String']['output']>;
  resp_01?: Maybe<Scalars['String']['output']>;
  resp_02?: Maybe<Scalars['String']['output']>;
  resp_03?: Maybe<Scalars['String']['output']>;
  art_01?: Maybe<Scalars['String']['output']>;
  art_02?: Maybe<Scalars['String']['output']>;
  art_03?: Maybe<Scalars['String']['output']>;
  art_04?: Maybe<Scalars['String']['output']>;
  apropos_01?: Maybe<Scalars['String']['output']>;
  apropos_02?: Maybe<Scalars['String']['output']>;
  apropos_03?: Maybe<Scalars['String']['output']>;
  apropos_04?: Maybe<Scalars['String']['output']>;
  apropos_05?: Maybe<Scalars['String']['output']>;
  apropos_06?: Maybe<Scalars['String']['output']>;
  apropos_07?: Maybe<Scalars['String']['output']>;
  apropos_08?: Maybe<Scalars['String']['output']>;
  apropos_09?: Maybe<Scalars['String']['output']>;
  soins_portrait?: Maybe<Scalars['String']['output']>;
  accomp_portrait?: Maybe<Scalars['String']['output']>;
  accomp_univers?: Maybe<Scalars['String']['output']>;
  quint_silence?: Maybe<Scalars['String']['output']>;
  quint_crea?: Maybe<Scalars['String']['output']>;
  quint_resp?: Maybe<Scalars['String']['output']>;
  quint_end?: Maybe<Scalars['String']['output']>;
  part_meiso?: Maybe<Scalars['String']['output']>;
  part_chanka?: Maybe<Scalars['String']['output']>;
  part_blast?: Maybe<Scalars['String']['output']>;
  part_tamakeapa?: Maybe<Scalars['String']['output']>;
  part_espriterre?: Maybe<Scalars['String']['output']>;
  part_koom?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImagesFilter = {
  hero_accueil?: InputMaybe<ImageFilter>;
  hero_soins?: InputMaybe<ImageFilter>;
  hero_accomp?: InputMaybe<ImageFilter>;
  hero_agenda?: InputMaybe<ImageFilter>;
  hero_apropos?: InputMaybe<ImageFilter>;
  hero_quintessence?: InputMaybe<ImageFilter>;
  hero_partenaires?: InputMaybe<ImageFilter>;
  hero_contact?: InputMaybe<ImageFilter>;
  accueil_portrait?: InputMaybe<ImageFilter>;
  accueil_ateliers?: InputMaybe<ImageFilter>;
  accueil_soins?: InputMaybe<ImageFilter>;
  accueil_accomp?: InputMaybe<ImageFilter>;
  accueil_immersions?: InputMaybe<ImageFilter>;
  resp_01?: InputMaybe<ImageFilter>;
  resp_02?: InputMaybe<ImageFilter>;
  resp_03?: InputMaybe<ImageFilter>;
  art_01?: InputMaybe<ImageFilter>;
  art_02?: InputMaybe<ImageFilter>;
  art_03?: InputMaybe<ImageFilter>;
  art_04?: InputMaybe<ImageFilter>;
  apropos_01?: InputMaybe<ImageFilter>;
  apropos_02?: InputMaybe<ImageFilter>;
  apropos_03?: InputMaybe<ImageFilter>;
  apropos_04?: InputMaybe<ImageFilter>;
  apropos_05?: InputMaybe<ImageFilter>;
  apropos_06?: InputMaybe<ImageFilter>;
  apropos_07?: InputMaybe<ImageFilter>;
  apropos_08?: InputMaybe<ImageFilter>;
  apropos_09?: InputMaybe<ImageFilter>;
  soins_portrait?: InputMaybe<ImageFilter>;
  accomp_portrait?: InputMaybe<ImageFilter>;
  accomp_univers?: InputMaybe<ImageFilter>;
  quint_silence?: InputMaybe<ImageFilter>;
  quint_crea?: InputMaybe<ImageFilter>;
  quint_resp?: InputMaybe<ImageFilter>;
  quint_end?: InputMaybe<ImageFilter>;
  part_meiso?: InputMaybe<ImageFilter>;
  part_chanka?: InputMaybe<ImageFilter>;
  part_blast?: InputMaybe<ImageFilter>;
  part_tamakeapa?: InputMaybe<ImageFilter>;
  part_espriterre?: InputMaybe<ImageFilter>;
  part_koom?: InputMaybe<ImageFilter>;
};

export type ImagesConnectionEdges = {
  __typename?: 'ImagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Images>;
};

export type ImagesConnection = Connection & {
  __typename?: 'ImagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ImagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAgenda: Agenda;
  createAgenda: Agenda;
  updateOffres: Offres;
  createOffres: Offres;
  updatePages: Pages;
  createPages: Pages;
  updatePage_apropos: Page_Apropos;
  createPage_apropos: Page_Apropos;
  updatePage_soins: Page_Soins;
  createPage_soins: Page_Soins;
  updatePage_accompagnement: Page_Accompagnement;
  createPage_accompagnement: Page_Accompagnement;
  updatePage_quintessence: Page_Quintessence;
  createPage_quintessence: Page_Quintessence;
  updatePage_contact: Page_Contact;
  createPage_contact: Page_Contact;
  updateImages: Images;
  createImages: Images;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAgendaArgs = {
  relativePath: Scalars['String']['input'];
  params: AgendaMutation;
};


export type MutationCreateAgendaArgs = {
  relativePath: Scalars['String']['input'];
  params: AgendaMutation;
};


export type MutationUpdateOffresArgs = {
  relativePath: Scalars['String']['input'];
  params: OffresMutation;
};


export type MutationCreateOffresArgs = {
  relativePath: Scalars['String']['input'];
  params: OffresMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdatePage_AproposArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_AproposMutation;
};


export type MutationCreatePage_AproposArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_AproposMutation;
};


export type MutationUpdatePage_SoinsArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_SoinsMutation;
};


export type MutationCreatePage_SoinsArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_SoinsMutation;
};


export type MutationUpdatePage_AccompagnementArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_AccompagnementMutation;
};


export type MutationCreatePage_AccompagnementArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_AccompagnementMutation;
};


export type MutationUpdatePage_QuintessenceArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_QuintessenceMutation;
};


export type MutationCreatePage_QuintessenceArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_QuintessenceMutation;
};


export type MutationUpdatePage_ContactArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_ContactMutation;
};


export type MutationCreatePage_ContactArgs = {
  relativePath: Scalars['String']['input'];
  params: Page_ContactMutation;
};


export type MutationUpdateImagesArgs = {
  relativePath: Scalars['String']['input'];
  params: ImagesMutation;
};


export type MutationCreateImagesArgs = {
  relativePath: Scalars['String']['input'];
  params: ImagesMutation;
};

export type DocumentUpdateMutation = {
  agenda?: InputMaybe<AgendaMutation>;
  offres?: InputMaybe<OffresMutation>;
  pages?: InputMaybe<PagesMutation>;
  page_apropos?: InputMaybe<Page_AproposMutation>;
  page_soins?: InputMaybe<Page_SoinsMutation>;
  page_accompagnement?: InputMaybe<Page_AccompagnementMutation>;
  page_quintessence?: InputMaybe<Page_QuintessenceMutation>;
  page_contact?: InputMaybe<Page_ContactMutation>;
  images?: InputMaybe<ImagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  agenda?: InputMaybe<AgendaMutation>;
  offres?: InputMaybe<OffresMutation>;
  pages?: InputMaybe<PagesMutation>;
  page_apropos?: InputMaybe<Page_AproposMutation>;
  page_soins?: InputMaybe<Page_SoinsMutation>;
  page_accompagnement?: InputMaybe<Page_AccompagnementMutation>;
  page_quintessence?: InputMaybe<Page_QuintessenceMutation>;
  page_contact?: InputMaybe<Page_ContactMutation>;
  images?: InputMaybe<ImagesMutation>;
};

export type AgendaMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  categorie?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  date_fin?: InputMaybe<Scalars['String']['input']>;
  rythme?: InputMaybe<Scalars['String']['input']>;
  heure?: InputMaybe<Scalars['String']['input']>;
  lieu?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  earlybird?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
  site?: InputMaybe<Scalars['String']['input']>;
  lien?: InputMaybe<Scalars['String']['input']>;
  resume?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  reservable?: InputMaybe<Scalars['Boolean']['input']>;
  ordre?: InputMaybe<Scalars['Float']['input']>;
  publie?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type OffresTarifsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  detail?: InputMaybe<Scalars['String']['input']>;
};

export type OffresMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  categorie?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  resume?: InputMaybe<Scalars['String']['input']>;
  prix?: InputMaybe<Scalars['String']['input']>;
  duree?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  tarifs?: InputMaybe<Array<InputMaybe<OffresTarifsMutation>>>;
  image?: InputMaybe<Scalars['String']['input']>;
  lien?: InputMaybe<Scalars['String']['input']>;
  reservable?: InputMaybe<Scalars['Boolean']['input']>;
  ordre?: InputMaybe<Scalars['Float']['input']>;
  publie?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type PagesPropositionsMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  texte?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
};

export type PagesMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  hero_accent?: InputMaybe<Scalars['String']['input']>;
  hero_paragraphe?: InputMaybe<Scalars['String']['input']>;
  hero_cta?: InputMaybe<Scalars['String']['input']>;
  piliers_titre?: InputMaybe<Scalars['String']['input']>;
  citation1?: InputMaybe<Scalars['String']['input']>;
  propositions_titre?: InputMaybe<Scalars['String']['input']>;
  propositions?: InputMaybe<Array<InputMaybe<PagesPropositionsMutation>>>;
  citation2?: InputMaybe<Scalars['String']['input']>;
  citation_contact?: InputMaybe<Scalars['String']['input']>;
  form_titre?: InputMaybe<Scalars['String']['input']>;
  form_intro?: InputMaybe<Scalars['String']['input']>;
};

export type Page_AproposChapitresMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  texte?: InputMaybe<Scalars['String']['input']>;
};

export type Page_AproposMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  chapitres?: InputMaybe<Array<InputMaybe<Page_AproposChapitresMutation>>>;
};

export type Page_SoinsMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  coeur?: InputMaybe<Scalars['String']['input']>;
  soins_eyebrow?: InputMaybe<Scalars['String']['input']>;
  soins_titre?: InputMaybe<Scalars['String']['input']>;
  soins_intro?: InputMaybe<Scalars['String']['input']>;
};

export type Page_AccompagnementMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  coeur?: InputMaybe<Scalars['String']['input']>;
  pourqui_eyebrow?: InputMaybe<Scalars['String']['input']>;
  pourqui_titre?: InputMaybe<Scalars['String']['input']>;
  pourqui_texte?: InputMaybe<Scalars['String']['input']>;
  outils_eyebrow?: InputMaybe<Scalars['String']['input']>;
  outils_titre?: InputMaybe<Scalars['String']['input']>;
  outils?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  passage?: InputMaybe<Scalars['String']['input']>;
  formules_eyebrow?: InputMaybe<Scalars['String']['input']>;
  formules_titre?: InputMaybe<Scalars['String']['input']>;
};

export type Page_QuintessenceMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  hero_lead?: InputMaybe<Scalars['String']['input']>;
  passage?: InputMaybe<Scalars['String']['input']>;
  citation?: InputMaybe<Scalars['String']['input']>;
  silence_titre?: InputMaybe<Scalars['String']['input']>;
  silence_texte?: InputMaybe<Scalars['String']['input']>;
  crea_titre?: InputMaybe<Scalars['String']['input']>;
  crea_texte?: InputMaybe<Scalars['String']['input']>;
  pratiques_eyebrow?: InputMaybe<Scalars['String']['input']>;
  pratiques_titre?: InputMaybe<Scalars['String']['input']>;
  pratiques?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  cta_texte?: InputMaybe<Scalars['String']['input']>;
};

export type Page_ContactMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
};

export type ImagesMutation = {
  hero_accueil?: InputMaybe<Scalars['String']['input']>;
  hero_soins?: InputMaybe<Scalars['String']['input']>;
  hero_accomp?: InputMaybe<Scalars['String']['input']>;
  hero_agenda?: InputMaybe<Scalars['String']['input']>;
  hero_apropos?: InputMaybe<Scalars['String']['input']>;
  hero_quintessence?: InputMaybe<Scalars['String']['input']>;
  hero_partenaires?: InputMaybe<Scalars['String']['input']>;
  hero_contact?: InputMaybe<Scalars['String']['input']>;
  accueil_portrait?: InputMaybe<Scalars['String']['input']>;
  accueil_ateliers?: InputMaybe<Scalars['String']['input']>;
  accueil_soins?: InputMaybe<Scalars['String']['input']>;
  accueil_accomp?: InputMaybe<Scalars['String']['input']>;
  accueil_immersions?: InputMaybe<Scalars['String']['input']>;
  resp_01?: InputMaybe<Scalars['String']['input']>;
  resp_02?: InputMaybe<Scalars['String']['input']>;
  resp_03?: InputMaybe<Scalars['String']['input']>;
  art_01?: InputMaybe<Scalars['String']['input']>;
  art_02?: InputMaybe<Scalars['String']['input']>;
  art_03?: InputMaybe<Scalars['String']['input']>;
  art_04?: InputMaybe<Scalars['String']['input']>;
  apropos_01?: InputMaybe<Scalars['String']['input']>;
  apropos_02?: InputMaybe<Scalars['String']['input']>;
  apropos_03?: InputMaybe<Scalars['String']['input']>;
  apropos_04?: InputMaybe<Scalars['String']['input']>;
  apropos_05?: InputMaybe<Scalars['String']['input']>;
  apropos_06?: InputMaybe<Scalars['String']['input']>;
  apropos_07?: InputMaybe<Scalars['String']['input']>;
  apropos_08?: InputMaybe<Scalars['String']['input']>;
  apropos_09?: InputMaybe<Scalars['String']['input']>;
  soins_portrait?: InputMaybe<Scalars['String']['input']>;
  accomp_portrait?: InputMaybe<Scalars['String']['input']>;
  accomp_univers?: InputMaybe<Scalars['String']['input']>;
  quint_silence?: InputMaybe<Scalars['String']['input']>;
  quint_crea?: InputMaybe<Scalars['String']['input']>;
  quint_resp?: InputMaybe<Scalars['String']['input']>;
  quint_end?: InputMaybe<Scalars['String']['input']>;
  part_meiso?: InputMaybe<Scalars['String']['input']>;
  part_chanka?: InputMaybe<Scalars['String']['input']>;
  part_blast?: InputMaybe<Scalars['String']['input']>;
  part_tamakeapa?: InputMaybe<Scalars['String']['input']>;
  part_espriterre?: InputMaybe<Scalars['String']['input']>;
  part_koom?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type DatetimeFilter = {
  after?: string | null | undefined;
  before?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type AgendaFilter = {
  titre?: StringFilter | null | undefined;
  categorie?: StringFilter | null | undefined;
  date?: DatetimeFilter | null | undefined;
  date_fin?: DatetimeFilter | null | undefined;
  rythme?: StringFilter | null | undefined;
  heure?: StringFilter | null | undefined;
  lieu?: StringFilter | null | undefined;
  prix?: StringFilter | null | undefined;
  earlybird?: StringFilter | null | undefined;
  cta?: StringFilter | null | undefined;
  site?: StringFilter | null | undefined;
  lien?: StringFilter | null | undefined;
  resume?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  reservable?: BooleanFilter | null | undefined;
  ordre?: NumberFilter | null | undefined;
  publie?: BooleanFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type OffresTarifsFilter = {
  label?: StringFilter | null | undefined;
  prix?: StringFilter | null | undefined;
  detail?: StringFilter | null | undefined;
};

export type OffresFilter = {
  titre?: StringFilter | null | undefined;
  categorie?: StringFilter | null | undefined;
  tag?: StringFilter | null | undefined;
  resume?: StringFilter | null | undefined;
  prix?: StringFilter | null | undefined;
  duree?: StringFilter | null | undefined;
  format?: StringFilter | null | undefined;
  tarifs?: OffresTarifsFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  lien?: StringFilter | null | undefined;
  reservable?: BooleanFilter | null | undefined;
  ordre?: NumberFilter | null | undefined;
  publie?: BooleanFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type PagesPropositionsFilter = {
  titre?: StringFilter | null | undefined;
  texte?: StringFilter | null | undefined;
  cta?: StringFilter | null | undefined;
};

export type PagesFilter = {
  hero_eyebrow?: StringFilter | null | undefined;
  hero_titre?: StringFilter | null | undefined;
  hero_accent?: StringFilter | null | undefined;
  hero_paragraphe?: StringFilter | null | undefined;
  hero_cta?: StringFilter | null | undefined;
  piliers_titre?: StringFilter | null | undefined;
  citation1?: StringFilter | null | undefined;
  propositions_titre?: StringFilter | null | undefined;
  propositions?: PagesPropositionsFilter | null | undefined;
  citation2?: StringFilter | null | undefined;
  citation_contact?: StringFilter | null | undefined;
  form_titre?: StringFilter | null | undefined;
  form_intro?: StringFilter | null | undefined;
};

export type Page_AproposChapitresFilter = {
  titre?: StringFilter | null | undefined;
  texte?: StringFilter | null | undefined;
};

export type Page_AproposFilter = {
  hero_eyebrow?: StringFilter | null | undefined;
  hero_titre?: StringFilter | null | undefined;
  chapitres?: Page_AproposChapitresFilter | null | undefined;
};

export type Page_SoinsFilter = {
  hero_eyebrow?: StringFilter | null | undefined;
  hero_titre?: StringFilter | null | undefined;
  coeur?: StringFilter | null | undefined;
  soins_eyebrow?: StringFilter | null | undefined;
  soins_titre?: StringFilter | null | undefined;
  soins_intro?: StringFilter | null | undefined;
};

export type Page_AccompagnementFilter = {
  hero_eyebrow?: StringFilter | null | undefined;
  hero_titre?: StringFilter | null | undefined;
  coeur?: StringFilter | null | undefined;
  pourqui_eyebrow?: StringFilter | null | undefined;
  pourqui_titre?: StringFilter | null | undefined;
  pourqui_texte?: StringFilter | null | undefined;
  outils_eyebrow?: StringFilter | null | undefined;
  outils_titre?: StringFilter | null | undefined;
  outils?: StringFilter | null | undefined;
  passage?: StringFilter | null | undefined;
  formules_eyebrow?: StringFilter | null | undefined;
  formules_titre?: StringFilter | null | undefined;
};

export type Page_QuintessenceFilter = {
  hero_eyebrow?: StringFilter | null | undefined;
  hero_titre?: StringFilter | null | undefined;
  hero_lead?: StringFilter | null | undefined;
  passage?: StringFilter | null | undefined;
  citation?: StringFilter | null | undefined;
  silence_titre?: StringFilter | null | undefined;
  silence_texte?: StringFilter | null | undefined;
  crea_titre?: StringFilter | null | undefined;
  crea_texte?: StringFilter | null | undefined;
  pratiques_eyebrow?: StringFilter | null | undefined;
  pratiques_titre?: StringFilter | null | undefined;
  pratiques?: StringFilter | null | undefined;
  cta_texte?: StringFilter | null | undefined;
};

export type Page_ContactFilter = {
  hero_eyebrow?: StringFilter | null | undefined;
  hero_titre?: StringFilter | null | undefined;
  intro?: StringFilter | null | undefined;
};

export type ImagesFilter = {
  hero_accueil?: ImageFilter | null | undefined;
  hero_soins?: ImageFilter | null | undefined;
  hero_accomp?: ImageFilter | null | undefined;
  hero_agenda?: ImageFilter | null | undefined;
  hero_apropos?: ImageFilter | null | undefined;
  hero_quintessence?: ImageFilter | null | undefined;
  hero_partenaires?: ImageFilter | null | undefined;
  hero_contact?: ImageFilter | null | undefined;
  accueil_portrait?: ImageFilter | null | undefined;
  accueil_ateliers?: ImageFilter | null | undefined;
  accueil_soins?: ImageFilter | null | undefined;
  accueil_accomp?: ImageFilter | null | undefined;
  accueil_immersions?: ImageFilter | null | undefined;
  resp_01?: ImageFilter | null | undefined;
  resp_02?: ImageFilter | null | undefined;
  resp_03?: ImageFilter | null | undefined;
  art_01?: ImageFilter | null | undefined;
  art_02?: ImageFilter | null | undefined;
  art_03?: ImageFilter | null | undefined;
  art_04?: ImageFilter | null | undefined;
  apropos_01?: ImageFilter | null | undefined;
  apropos_02?: ImageFilter | null | undefined;
  apropos_03?: ImageFilter | null | undefined;
  apropos_04?: ImageFilter | null | undefined;
  apropos_05?: ImageFilter | null | undefined;
  apropos_06?: ImageFilter | null | undefined;
  apropos_07?: ImageFilter | null | undefined;
  apropos_08?: ImageFilter | null | undefined;
  apropos_09?: ImageFilter | null | undefined;
  soins_portrait?: ImageFilter | null | undefined;
  accomp_portrait?: ImageFilter | null | undefined;
  accomp_univers?: ImageFilter | null | undefined;
  quint_silence?: ImageFilter | null | undefined;
  quint_crea?: ImageFilter | null | undefined;
  quint_resp?: ImageFilter | null | undefined;
  quint_end?: ImageFilter | null | undefined;
  part_meiso?: ImageFilter | null | undefined;
  part_chanka?: ImageFilter | null | undefined;
  part_blast?: ImageFilter | null | undefined;
  part_tamakeapa?: ImageFilter | null | undefined;
  part_espriterre?: ImageFilter | null | undefined;
  part_koom?: ImageFilter | null | undefined;
};

export type AgendaPartsFragment = { __typename: 'Agenda', titre: string, categorie: string, date: string | null, date_fin: string | null, rythme: string | null, heure: string | null, lieu: string | null, prix: string | null, earlybird: string | null, cta: string | null, site: string | null, lien: string | null, resume: string | null, image: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null };

export type OffresPartsFragment = { __typename: 'Offres', titre: string, categorie: string, tag: string | null, resume: string | null, prix: string | null, duree: string | null, format: string | null, image: string | null, lien: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, tarifs: Array<{ __typename: 'OffresTarifs', label: string | null, prix: string | null, detail: string | null } | null> | null };

export type PagesPartsFragment = { __typename: 'Pages', hero_eyebrow: string | null, hero_titre: string | null, hero_accent: string | null, hero_paragraphe: string | null, hero_cta: string | null, piliers_titre: string | null, citation1: string | null, propositions_titre: string | null, citation2: string | null, citation_contact: string | null, form_titre: string | null, form_intro: string | null, propositions: Array<{ __typename: 'PagesPropositions', titre: string | null, texte: string | null, cta: string | null } | null> | null };

export type Page_AproposPartsFragment = { __typename: 'Page_apropos', hero_eyebrow: string | null, hero_titre: string | null, chapitres: Array<{ __typename: 'Page_aproposChapitres', titre: string | null, texte: string | null } | null> | null };

export type Page_SoinsPartsFragment = { __typename: 'Page_soins', hero_eyebrow: string | null, hero_titre: string | null, coeur: string | null, soins_eyebrow: string | null, soins_titre: string | null, soins_intro: string | null };

export type Page_AccompagnementPartsFragment = { __typename: 'Page_accompagnement', hero_eyebrow: string | null, hero_titre: string | null, coeur: string | null, pourqui_eyebrow: string | null, pourqui_titre: string | null, pourqui_texte: string | null, outils_eyebrow: string | null, outils_titre: string | null, outils: Array<string | null> | null, passage: string | null, formules_eyebrow: string | null, formules_titre: string | null };

export type Page_QuintessencePartsFragment = { __typename: 'Page_quintessence', hero_eyebrow: string | null, hero_titre: string | null, hero_lead: string | null, passage: string | null, citation: string | null, silence_titre: string | null, silence_texte: string | null, crea_titre: string | null, crea_texte: string | null, pratiques_eyebrow: string | null, pratiques_titre: string | null, pratiques: Array<string | null> | null, cta_texte: string | null };

export type Page_ContactPartsFragment = { __typename: 'Page_contact', hero_eyebrow: string | null, hero_titre: string | null, intro: string | null };

export type ImagesPartsFragment = { __typename: 'Images', hero_accueil: string | null, hero_soins: string | null, hero_accomp: string | null, hero_agenda: string | null, hero_apropos: string | null, hero_quintessence: string | null, hero_partenaires: string | null, hero_contact: string | null, accueil_portrait: string | null, accueil_ateliers: string | null, accueil_soins: string | null, accueil_accomp: string | null, accueil_immersions: string | null, resp_01: string | null, resp_02: string | null, resp_03: string | null, art_01: string | null, art_02: string | null, art_03: string | null, art_04: string | null, apropos_01: string | null, apropos_02: string | null, apropos_03: string | null, apropos_04: string | null, apropos_05: string | null, apropos_06: string | null, apropos_07: string | null, apropos_08: string | null, apropos_09: string | null, soins_portrait: string | null, accomp_portrait: string | null, accomp_univers: string | null, quint_silence: string | null, quint_crea: string | null, quint_resp: string | null, quint_end: string | null, part_meiso: string | null, part_chanka: string | null, part_blast: string | null, part_tamakeapa: string | null, part_espriterre: string | null, part_koom: string | null };

export type AgendaQueryVariables = Exact<{
  relativePath: string;
}>;


export type AgendaQuery = { agenda: { __typename: 'Agenda', id: string, titre: string, categorie: string, date: string | null, date_fin: string | null, rythme: string | null, heure: string | null, lieu: string | null, prix: string | null, earlybird: string | null, cta: string | null, site: string | null, lien: string | null, resume: string | null, image: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AgendaConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: AgendaFilter | null | undefined;
}>;


export type AgendaConnectionQuery = { agendaConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Agenda', id: string, titre: string, categorie: string, date: string | null, date_fin: string | null, rythme: string | null, heure: string | null, lieu: string | null, prix: string | null, earlybird: string | null, cta: string | null, site: string | null, lien: string | null, resume: string | null, image: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type OffresQueryVariables = Exact<{
  relativePath: string;
}>;


export type OffresQuery = { offres: { __typename: 'Offres', id: string, titre: string, categorie: string, tag: string | null, resume: string | null, prix: string | null, duree: string | null, format: string | null, image: string | null, lien: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, tarifs: Array<{ __typename: 'OffresTarifs', label: string | null, prix: string | null, detail: string | null } | null> | null } };

export type OffresConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: OffresFilter | null | undefined;
}>;


export type OffresConnectionQuery = { offresConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Offres', id: string, titre: string, categorie: string, tag: string | null, resume: string | null, prix: string | null, duree: string | null, format: string | null, image: string | null, lien: string | null, reservable: boolean | null, ordre: number | null, publie: boolean | null, body: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, tarifs: Array<{ __typename: 'OffresTarifs', label: string | null, prix: string | null, detail: string | null } | null> | null } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type PagesQuery = { pages: { __typename: 'Pages', id: string, hero_eyebrow: string | null, hero_titre: string | null, hero_accent: string | null, hero_paragraphe: string | null, hero_cta: string | null, piliers_titre: string | null, citation1: string | null, propositions_titre: string | null, citation2: string | null, citation_contact: string | null, form_titre: string | null, form_intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, propositions: Array<{ __typename: 'PagesPropositions', titre: string | null, texte: string | null, cta: string | null } | null> | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PagesFilter | null | undefined;
}>;


export type PagesConnectionQuery = { pagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Pages', id: string, hero_eyebrow: string | null, hero_titre: string | null, hero_accent: string | null, hero_paragraphe: string | null, hero_cta: string | null, piliers_titre: string | null, citation1: string | null, propositions_titre: string | null, citation2: string | null, citation_contact: string | null, form_titre: string | null, form_intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, propositions: Array<{ __typename: 'PagesPropositions', titre: string | null, texte: string | null, cta: string | null } | null> | null } | null } | null> | null } };

export type Page_AproposQueryVariables = Exact<{
  relativePath: string;
}>;


export type Page_AproposQuery = { page_apropos: { __typename: 'Page_apropos', id: string, hero_eyebrow: string | null, hero_titre: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, chapitres: Array<{ __typename: 'Page_aproposChapitres', titre: string | null, texte: string | null } | null> | null } };

export type Page_AproposConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Page_AproposFilter | null | undefined;
}>;


export type Page_AproposConnectionQuery = { page_aproposConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page_apropos', id: string, hero_eyebrow: string | null, hero_titre: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, chapitres: Array<{ __typename: 'Page_aproposChapitres', titre: string | null, texte: string | null } | null> | null } | null } | null> | null } };

export type Page_SoinsQueryVariables = Exact<{
  relativePath: string;
}>;


export type Page_SoinsQuery = { page_soins: { __typename: 'Page_soins', id: string, hero_eyebrow: string | null, hero_titre: string | null, coeur: string | null, soins_eyebrow: string | null, soins_titre: string | null, soins_intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Page_SoinsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Page_SoinsFilter | null | undefined;
}>;


export type Page_SoinsConnectionQuery = { page_soinsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page_soins', id: string, hero_eyebrow: string | null, hero_titre: string | null, coeur: string | null, soins_eyebrow: string | null, soins_titre: string | null, soins_intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Page_AccompagnementQueryVariables = Exact<{
  relativePath: string;
}>;


export type Page_AccompagnementQuery = { page_accompagnement: { __typename: 'Page_accompagnement', id: string, hero_eyebrow: string | null, hero_titre: string | null, coeur: string | null, pourqui_eyebrow: string | null, pourqui_titre: string | null, pourqui_texte: string | null, outils_eyebrow: string | null, outils_titre: string | null, outils: Array<string | null> | null, passage: string | null, formules_eyebrow: string | null, formules_titre: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Page_AccompagnementConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Page_AccompagnementFilter | null | undefined;
}>;


export type Page_AccompagnementConnectionQuery = { page_accompagnementConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page_accompagnement', id: string, hero_eyebrow: string | null, hero_titre: string | null, coeur: string | null, pourqui_eyebrow: string | null, pourqui_titre: string | null, pourqui_texte: string | null, outils_eyebrow: string | null, outils_titre: string | null, outils: Array<string | null> | null, passage: string | null, formules_eyebrow: string | null, formules_titre: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Page_QuintessenceQueryVariables = Exact<{
  relativePath: string;
}>;


export type Page_QuintessenceQuery = { page_quintessence: { __typename: 'Page_quintessence', id: string, hero_eyebrow: string | null, hero_titre: string | null, hero_lead: string | null, passage: string | null, citation: string | null, silence_titre: string | null, silence_texte: string | null, crea_titre: string | null, crea_texte: string | null, pratiques_eyebrow: string | null, pratiques_titre: string | null, pratiques: Array<string | null> | null, cta_texte: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Page_QuintessenceConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Page_QuintessenceFilter | null | undefined;
}>;


export type Page_QuintessenceConnectionQuery = { page_quintessenceConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page_quintessence', id: string, hero_eyebrow: string | null, hero_titre: string | null, hero_lead: string | null, passage: string | null, citation: string | null, silence_titre: string | null, silence_texte: string | null, crea_titre: string | null, crea_texte: string | null, pratiques_eyebrow: string | null, pratiques_titre: string | null, pratiques: Array<string | null> | null, cta_texte: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Page_ContactQueryVariables = Exact<{
  relativePath: string;
}>;


export type Page_ContactQuery = { page_contact: { __typename: 'Page_contact', id: string, hero_eyebrow: string | null, hero_titre: string | null, intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Page_ContactConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Page_ContactFilter | null | undefined;
}>;


export type Page_ContactConnectionQuery = { page_contactConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page_contact', id: string, hero_eyebrow: string | null, hero_titre: string | null, intro: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ImagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type ImagesQuery = { images: { __typename: 'Images', id: string, hero_accueil: string | null, hero_soins: string | null, hero_accomp: string | null, hero_agenda: string | null, hero_apropos: string | null, hero_quintessence: string | null, hero_partenaires: string | null, hero_contact: string | null, accueil_portrait: string | null, accueil_ateliers: string | null, accueil_soins: string | null, accueil_accomp: string | null, accueil_immersions: string | null, resp_01: string | null, resp_02: string | null, resp_03: string | null, art_01: string | null, art_02: string | null, art_03: string | null, art_04: string | null, apropos_01: string | null, apropos_02: string | null, apropos_03: string | null, apropos_04: string | null, apropos_05: string | null, apropos_06: string | null, apropos_07: string | null, apropos_08: string | null, apropos_09: string | null, soins_portrait: string | null, accomp_portrait: string | null, accomp_univers: string | null, quint_silence: string | null, quint_crea: string | null, quint_resp: string | null, quint_end: string | null, part_meiso: string | null, part_chanka: string | null, part_blast: string | null, part_tamakeapa: string | null, part_espriterre: string | null, part_koom: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ImagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ImagesFilter | null | undefined;
}>;


export type ImagesConnectionQuery = { imagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Images', id: string, hero_accueil: string | null, hero_soins: string | null, hero_accomp: string | null, hero_agenda: string | null, hero_apropos: string | null, hero_quintessence: string | null, hero_partenaires: string | null, hero_contact: string | null, accueil_portrait: string | null, accueil_ateliers: string | null, accueil_soins: string | null, accueil_accomp: string | null, accueil_immersions: string | null, resp_01: string | null, resp_02: string | null, resp_03: string | null, art_01: string | null, art_02: string | null, art_03: string | null, art_04: string | null, apropos_01: string | null, apropos_02: string | null, apropos_03: string | null, apropos_04: string | null, apropos_05: string | null, apropos_06: string | null, apropos_07: string | null, apropos_08: string | null, apropos_09: string | null, soins_portrait: string | null, accomp_portrait: string | null, accomp_univers: string | null, quint_silence: string | null, quint_crea: string | null, quint_resp: string | null, quint_end: string | null, part_meiso: string | null, part_chanka: string | null, part_blast: string | null, part_tamakeapa: string | null, part_espriterre: string | null, part_koom: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const AgendaPartsFragmentDoc = gql`
    fragment AgendaParts on Agenda {
  __typename
  titre
  categorie
  date
  date_fin
  rythme
  heure
  lieu
  prix
  earlybird
  cta
  site
  lien
  resume
  image
  reservable
  ordre
  publie
  body
}
    `;
export const OffresPartsFragmentDoc = gql`
    fragment OffresParts on Offres {
  __typename
  titre
  categorie
  tag
  resume
  prix
  duree
  format
  tarifs {
    __typename
    label
    prix
    detail
  }
  image
  lien
  reservable
  ordre
  publie
  body
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  hero_eyebrow
  hero_titre
  hero_accent
  hero_paragraphe
  hero_cta
  piliers_titre
  citation1
  propositions_titre
  propositions {
    __typename
    titre
    texte
    cta
  }
  citation2
  citation_contact
  form_titre
  form_intro
}
    `;
export const Page_AproposPartsFragmentDoc = gql`
    fragment Page_aproposParts on Page_apropos {
  __typename
  hero_eyebrow
  hero_titre
  chapitres {
    __typename
    titre
    texte
  }
}
    `;
export const Page_SoinsPartsFragmentDoc = gql`
    fragment Page_soinsParts on Page_soins {
  __typename
  hero_eyebrow
  hero_titre
  coeur
  soins_eyebrow
  soins_titre
  soins_intro
}
    `;
export const Page_AccompagnementPartsFragmentDoc = gql`
    fragment Page_accompagnementParts on Page_accompagnement {
  __typename
  hero_eyebrow
  hero_titre
  coeur
  pourqui_eyebrow
  pourqui_titre
  pourqui_texte
  outils_eyebrow
  outils_titre
  outils
  passage
  formules_eyebrow
  formules_titre
}
    `;
export const Page_QuintessencePartsFragmentDoc = gql`
    fragment Page_quintessenceParts on Page_quintessence {
  __typename
  hero_eyebrow
  hero_titre
  hero_lead
  passage
  citation
  silence_titre
  silence_texte
  crea_titre
  crea_texte
  pratiques_eyebrow
  pratiques_titre
  pratiques
  cta_texte
}
    `;
export const Page_ContactPartsFragmentDoc = gql`
    fragment Page_contactParts on Page_contact {
  __typename
  hero_eyebrow
  hero_titre
  intro
}
    `;
export const ImagesPartsFragmentDoc = gql`
    fragment ImagesParts on Images {
  __typename
  hero_accueil
  hero_soins
  hero_accomp
  hero_agenda
  hero_apropos
  hero_quintessence
  hero_partenaires
  hero_contact
  accueil_portrait
  accueil_ateliers
  accueil_soins
  accueil_accomp
  accueil_immersions
  resp_01
  resp_02
  resp_03
  art_01
  art_02
  art_03
  art_04
  apropos_01
  apropos_02
  apropos_03
  apropos_04
  apropos_05
  apropos_06
  apropos_07
  apropos_08
  apropos_09
  soins_portrait
  accomp_portrait
  accomp_univers
  quint_silence
  quint_crea
  quint_resp
  quint_end
  part_meiso
  part_chanka
  part_blast
  part_tamakeapa
  part_espriterre
  part_koom
}
    `;
export const AgendaDocument = gql`
    query agenda($relativePath: String!) {
  agenda(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AgendaParts
  }
}
    ${AgendaPartsFragmentDoc}`;
export const AgendaConnectionDocument = gql`
    query agendaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AgendaFilter) {
  agendaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AgendaParts
      }
    }
  }
}
    ${AgendaPartsFragmentDoc}`;
export const OffresDocument = gql`
    query offres($relativePath: String!) {
  offres(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OffresParts
  }
}
    ${OffresPartsFragmentDoc}`;
export const OffresConnectionDocument = gql`
    query offresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OffresFilter) {
  offresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OffresParts
      }
    }
  }
}
    ${OffresPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const Page_AproposDocument = gql`
    query page_apropos($relativePath: String!) {
  page_apropos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Page_aproposParts
  }
}
    ${Page_AproposPartsFragmentDoc}`;
export const Page_AproposConnectionDocument = gql`
    query page_aproposConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Page_aproposFilter) {
  page_aproposConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Page_aproposParts
      }
    }
  }
}
    ${Page_AproposPartsFragmentDoc}`;
export const Page_SoinsDocument = gql`
    query page_soins($relativePath: String!) {
  page_soins(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Page_soinsParts
  }
}
    ${Page_SoinsPartsFragmentDoc}`;
export const Page_SoinsConnectionDocument = gql`
    query page_soinsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Page_soinsFilter) {
  page_soinsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Page_soinsParts
      }
    }
  }
}
    ${Page_SoinsPartsFragmentDoc}`;
export const Page_AccompagnementDocument = gql`
    query page_accompagnement($relativePath: String!) {
  page_accompagnement(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Page_accompagnementParts
  }
}
    ${Page_AccompagnementPartsFragmentDoc}`;
export const Page_AccompagnementConnectionDocument = gql`
    query page_accompagnementConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Page_accompagnementFilter) {
  page_accompagnementConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Page_accompagnementParts
      }
    }
  }
}
    ${Page_AccompagnementPartsFragmentDoc}`;
export const Page_QuintessenceDocument = gql`
    query page_quintessence($relativePath: String!) {
  page_quintessence(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Page_quintessenceParts
  }
}
    ${Page_QuintessencePartsFragmentDoc}`;
export const Page_QuintessenceConnectionDocument = gql`
    query page_quintessenceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Page_quintessenceFilter) {
  page_quintessenceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Page_quintessenceParts
      }
    }
  }
}
    ${Page_QuintessencePartsFragmentDoc}`;
export const Page_ContactDocument = gql`
    query page_contact($relativePath: String!) {
  page_contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Page_contactParts
  }
}
    ${Page_ContactPartsFragmentDoc}`;
export const Page_ContactConnectionDocument = gql`
    query page_contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Page_contactFilter) {
  page_contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Page_contactParts
      }
    }
  }
}
    ${Page_ContactPartsFragmentDoc}`;
export const ImagesDocument = gql`
    query images($relativePath: String!) {
  images(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ImagesParts
  }
}
    ${ImagesPartsFragmentDoc}`;
export const ImagesConnectionDocument = gql`
    query imagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ImagesFilter) {
  imagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ImagesParts
      }
    }
  }
}
    ${ImagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      agenda(variables: AgendaQueryVariables, options?: C): Promise<{data: AgendaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaQueryVariables, query: string}> {
        return requester<{data: AgendaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaQueryVariables, query: string}, AgendaQueryVariables>(AgendaDocument, variables, options);
      },
    agendaConnection(variables?: AgendaConnectionQueryVariables, options?: C): Promise<{data: AgendaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaConnectionQueryVariables, query: string}> {
        return requester<{data: AgendaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AgendaConnectionQueryVariables, query: string}, AgendaConnectionQueryVariables>(AgendaConnectionDocument, variables, options);
      },
    offres(variables: OffresQueryVariables, options?: C): Promise<{data: OffresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresQueryVariables, query: string}> {
        return requester<{data: OffresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresQueryVariables, query: string}, OffresQueryVariables>(OffresDocument, variables, options);
      },
    offresConnection(variables?: OffresConnectionQueryVariables, options?: C): Promise<{data: OffresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresConnectionQueryVariables, query: string}> {
        return requester<{data: OffresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OffresConnectionQueryVariables, query: string}, OffresConnectionQueryVariables>(OffresConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    page_apropos(variables: Page_AproposQueryVariables, options?: C): Promise<{data: Page_AproposQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AproposQueryVariables, query: string}> {
        return requester<{data: Page_AproposQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AproposQueryVariables, query: string}, Page_AproposQueryVariables>(Page_AproposDocument, variables, options);
      },
    page_aproposConnection(variables?: Page_AproposConnectionQueryVariables, options?: C): Promise<{data: Page_AproposConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AproposConnectionQueryVariables, query: string}> {
        return requester<{data: Page_AproposConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AproposConnectionQueryVariables, query: string}, Page_AproposConnectionQueryVariables>(Page_AproposConnectionDocument, variables, options);
      },
    page_soins(variables: Page_SoinsQueryVariables, options?: C): Promise<{data: Page_SoinsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_SoinsQueryVariables, query: string}> {
        return requester<{data: Page_SoinsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_SoinsQueryVariables, query: string}, Page_SoinsQueryVariables>(Page_SoinsDocument, variables, options);
      },
    page_soinsConnection(variables?: Page_SoinsConnectionQueryVariables, options?: C): Promise<{data: Page_SoinsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_SoinsConnectionQueryVariables, query: string}> {
        return requester<{data: Page_SoinsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_SoinsConnectionQueryVariables, query: string}, Page_SoinsConnectionQueryVariables>(Page_SoinsConnectionDocument, variables, options);
      },
    page_accompagnement(variables: Page_AccompagnementQueryVariables, options?: C): Promise<{data: Page_AccompagnementQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AccompagnementQueryVariables, query: string}> {
        return requester<{data: Page_AccompagnementQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AccompagnementQueryVariables, query: string}, Page_AccompagnementQueryVariables>(Page_AccompagnementDocument, variables, options);
      },
    page_accompagnementConnection(variables?: Page_AccompagnementConnectionQueryVariables, options?: C): Promise<{data: Page_AccompagnementConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AccompagnementConnectionQueryVariables, query: string}> {
        return requester<{data: Page_AccompagnementConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_AccompagnementConnectionQueryVariables, query: string}, Page_AccompagnementConnectionQueryVariables>(Page_AccompagnementConnectionDocument, variables, options);
      },
    page_quintessence(variables: Page_QuintessenceQueryVariables, options?: C): Promise<{data: Page_QuintessenceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_QuintessenceQueryVariables, query: string}> {
        return requester<{data: Page_QuintessenceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_QuintessenceQueryVariables, query: string}, Page_QuintessenceQueryVariables>(Page_QuintessenceDocument, variables, options);
      },
    page_quintessenceConnection(variables?: Page_QuintessenceConnectionQueryVariables, options?: C): Promise<{data: Page_QuintessenceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_QuintessenceConnectionQueryVariables, query: string}> {
        return requester<{data: Page_QuintessenceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_QuintessenceConnectionQueryVariables, query: string}, Page_QuintessenceConnectionQueryVariables>(Page_QuintessenceConnectionDocument, variables, options);
      },
    page_contact(variables: Page_ContactQueryVariables, options?: C): Promise<{data: Page_ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_ContactQueryVariables, query: string}> {
        return requester<{data: Page_ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_ContactQueryVariables, query: string}, Page_ContactQueryVariables>(Page_ContactDocument, variables, options);
      },
    page_contactConnection(variables?: Page_ContactConnectionQueryVariables, options?: C): Promise<{data: Page_ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_ContactConnectionQueryVariables, query: string}> {
        return requester<{data: Page_ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Page_ContactConnectionQueryVariables, query: string}, Page_ContactConnectionQueryVariables>(Page_ContactConnectionDocument, variables, options);
      },
    images(variables: ImagesQueryVariables, options?: C): Promise<{data: ImagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImagesQueryVariables, query: string}> {
        return requester<{data: ImagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImagesQueryVariables, query: string}, ImagesQueryVariables>(ImagesDocument, variables, options);
      },
    imagesConnection(variables?: ImagesConnectionQueryVariables, options?: C): Promise<{data: ImagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImagesConnectionQueryVariables, query: string}> {
        return requester<{data: ImagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImagesConnectionQueryVariables, query: string}, ImagesConnectionQueryVariables>(ImagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/3.0/content/ac005920-bdf5-45df-a7d6-5d99cc50423a/github/tina",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  