import { defineConfig } from "tinacms";

const branch =
  process.env.BRANCH ||
  process.env.HEAD ||
  process.env.GITHUB_BRANCH ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  "tina";

export default defineConfig({
  branch,
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID || "ac005920-bdf5-45df-a7d6-5d99cc50423a",
  token: process.env.TINA_TOKEN || "",
  build: { outputFolder: "admin", publicFolder: "public" },
  media: { tina: { mediaRoot: "img", publicFolder: "public" } },
  schema: {
    collections: [
      {
        name: "agenda",
        label: "Agenda — événements",
        path: "src/content/agenda",
        format: "md",
        fields: [
          { type: "string", name: "titre", label: "Titre", isTitle: true, required: true },
          { type: "string", name: "categorie", label: "Catégorie", required: true,
            options: ["soin", "atelier", "retraite", "immersion", "voyage-sonore", "accompagnement", "cercle", "residence"] },
          { type: "datetime", name: "date", label: "Date", ui: { dateFormat: "YYYY-MM-DD" } },
          { type: "datetime", name: "date_fin", label: "Date de fin", ui: { dateFormat: "YYYY-MM-DD" } },
          { type: "string", name: "rythme", label: "Rythme (si pas de date)" },
          { type: "string", name: "heure", label: "Heure" },
          { type: "string", name: "lieu", label: "Lieu" },
          { type: "string", name: "prix", label: "Prix" },
          { type: "string", name: "earlybird", label: "Early bird — date limite" },
          { type: "string", name: "cta", label: "Texte du bouton" },
          { type: "string", name: "site", label: "Lien direct de la carte" },
          { type: "string", name: "lien", label: "Lien de réservation" },
          { type: "string", name: "resume", label: "Résumé", ui: { component: "textarea" } },
          { type: "image", name: "image", label: "Image" },
          { type: "boolean", name: "reservable", label: "Réservable" },
          { type: "number", name: "ordre", label: "Ordre d'affichage" },
          { type: "boolean", name: "publie", label: "Publié" },
          { type: "rich-text", name: "body", label: "Contenu de la page", isBody: true },
        ],
      },
      {
        name: "offres",
        label: "Soins & accompagnements",
        path: "src/content/offres",
        format: "md",
        fields: [
          { type: "string", name: "titre", label: "Titre", isTitle: true, required: true },
          { type: "string", name: "categorie", label: "Catégorie", required: true, options: ["soin", "accompagnement"] },
          { type: "string", name: "tag", label: "Étiquette" },
          { type: "string", name: "resume", label: "Résumé", ui: { component: "textarea" } },
          { type: "string", name: "prix", label: "Prix" },
          { type: "string", name: "duree", label: "Durée" },
          { type: "string", name: "format", label: "Format" },
          { type: "object", name: "tarifs", label: "Tarifs (formules)", list: true,
            ui: { itemProps: (i) => ({ label: i?.label ? `${i.label} — ${i.prix ?? ""}` : "Formule" }) },
            fields: [
              { type: "string", name: "label", label: "Formule" },
              { type: "string", name: "prix", label: "Prix" },
              { type: "string", name: "detail", label: "Détail" },
            ],
          },
          { type: "image", name: "image", label: "Image" },
          { type: "string", name: "lien", label: "Lien" },
          { type: "boolean", name: "reservable", label: "Réservable" },
          { type: "number", name: "ordre", label: "Ordre d'affichage" },
          { type: "boolean", name: "publie", label: "Publié" },
          { type: "rich-text", name: "body", label: "Contenu de la page", isBody: true },
        ],
      },
      {
        name: "pages",
        label: "Accueil",
        path: "src/content/pages",
        format: "md",
        match: { include: "accueil" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Hero — sur-titre" },
          { type: "string", name: "hero_titre", label: "Hero — titre (sans-serif)" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "image", name: "portrait_image", label: "Photo — Qui je suis" },
          { type: "image", name: "resp1_image", label: "Respiration 1 (fond)" },
          { type: "image", name: "resp2_image", label: "Respiration 2 (fond)" },
          { type: "image", name: "resp3_image", label: "Respiration bas (fond)" },
          { type: "image", name: "art1_image", label: "Oeuvre 1" },
          { type: "image", name: "art2_image", label: "Oeuvre 2" },
          { type: "image", name: "art3_image", label: "Oeuvre 3" },
          { type: "image", name: "art4_image", label: "Oeuvre 4" },
          { type: "string", name: "hero_accent", label: "Hero — accent manuscrit" },
          { type: "string", name: "hero_paragraphe", label: "Hero — paragraphe", description: "Entoure un mot de *etoiles* pour la manuscrite, de **deux** pour le dore.", ui: { component: "textarea" } },
          { type: "string", name: "hero_cta", label: "Hero — bouton" },
          { type: "string", name: "parcours_titre", label: "Qui je suis — titre", description: "*mot* = manuscrite" },
          { type: "string", name: "parcours_texte", label: "Qui je suis — texte", ui: { component: "textarea" } },
          { type: "string", name: "parcours_cta", label: "Qui je suis — bouton" },
          { type: "string", name: "piliers_eyebrow", label: "Piliers — sur-titre" },
          { type: "string", name: "agenda_eyebrow", label: "Agenda — sur-titre" },
          { type: "string", name: "art_eyebrow", label: "Art — sur-titre" },
          { type: "string", name: "art_titre", label: "Art — titre", description: "*mot* = manuscrite" },
          { type: "string", name: "temoins_eyebrow", label: "Temoignages — sur-titre" },
          { type: "object", name: "temoins", label: "Temoignages", list: true,
            ui: { itemProps: (i) => ({ label: i && i.n ? i.n : "Temoignage" }) },
            fields: [
              { type: "string", name: "t", label: "Texte", ui: { component: "textarea" } },
              { type: "string", name: "n", label: "Nom" },
              { type: "string", name: "c", label: "Contexte" },
            ] },
          { type: "string", name: "partenaires_eyebrow", label: "Partenaires — sur-titre" },
          { type: "string", name: "form_eyebrow", label: "Formulaire — sur-titre" },
          { type: "string", name: "piliers_titre", label: "Piliers — titre", description: "*mot* = manuscrite" },
          { type: "object", name: "piliers", label: "Piliers (les 5 univers)", list: true,
            ui: { itemProps: (i) => ({ label: i && i.nom ? i.nom : "Pilier" }) },
            fields: [
              { type: "string", name: "nom", label: "Nom" },
              { type: "string", name: "note", label: "Note (sous le nom)" },
            ] },
          { type: "string", name: "citation1", label: "Citation 1", description: "*mot* = manuscrite" },
          { type: "string", name: "propositions_titre", label: "Propositions — titre", description: "*mot* = manuscrite" },
          { type: "object", name: "propositions", label: "Propositions", list: true,
            ui: { itemProps: (i) => ({ label: i && i.titre ? i.titre : "Proposition" }) },
            fields: [
              { type: "string", name: "titre", label: "Titre" },
              { type: "string", name: "texte", label: "Texte", ui: { component: "textarea" } },
              { type: "string", name: "cta", label: "Bouton" },
              { type: "image", name: "image", label: "Photo" },
            ] },
          { type: "string", name: "citation2", label: "Citation 2", description: "*mot* = manuscrite" },
          { type: "string", name: "citation_contact", label: "Contact — phrase" },
          { type: "string", name: "form_titre", label: "Formulaire — titre", description: "*mot* = manuscrite" },
          { type: "string", name: "form_intro", label: "Formulaire — intro", ui: { component: "textarea" } },
        ],
      },
      {
        name: "page_apropos",
        label: "À propos",
        path: "src/content/pages",
        format: "md",
        match: { include: "a-propos" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "object", name: "chapitres", label: "Chapitres", list: true,
            ui: { itemProps: (i) => ({ label: i && i.titre ? i.titre : "Chapitre" }) },
            fields: [
              { type: "string", name: "titre", label: "Titre du chapitre" },
              { type: "string", name: "texte", label: "Texte (paragraphes separes par une ligne vide)", ui: { component: "textarea" } },
              { type: "image", name: "image", label: "Photo du chapitre" },
            ] },
        ],
      },
      {
        name: "page_soins",
        label: "Page Soins",
        path: "src/content/pages",
        format: "md",
        match: { include: "soins" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "image", name: "portrait_image", label: "Portrait" },
          { type: "string", name: "coeur", label: "Texte d'intro (coeur a coeur)", description: "**mot** = dore, *mot* = manuscrite. Paragraphes separes par une ligne vide.", ui: { component: "textarea" } },
          { type: "string", name: "soins_eyebrow", label: "Section soins — sur-titre" },
          { type: "string", name: "soins_titre", label: "Section soins — titre" },
          { type: "string", name: "soins_intro", label: "Section soins — intro", ui: { component: "textarea" } },
        ],
      },
      {
        name: "page_accompagnement",
        label: "Page Accompagnement",
        path: "src/content/pages",
        format: "md",
        match: { include: "accompagnement" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "string", name: "coeur", label: "Texte coeur a coeur", description: "**dore**, *manuscrite*, paragraphes = ligne vide", ui: { component: "textarea" } },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "image", name: "portrait_image", label: "Portrait" },
          { type: "image", name: "outils_image", label: "Image des outils" },
          { type: "string", name: "pourqui_eyebrow", label: "Pour qui — sur-titre" },
          { type: "string", name: "pourqui_titre", label: "Pour qui — titre" },
          { type: "string", name: "pourqui_texte", label: "Pour qui — texte", ui: { component: "textarea" } },
          { type: "string", name: "outils_eyebrow", label: "Outils — sur-titre" },
          { type: "string", name: "outils_titre", label: "Outils — titre" },
          { type: "string", name: "outils", label: "Outils (liste)", list: true },
          { type: "string", name: "passage", label: "Phrase mise en avant", ui: { component: "textarea" } },
          { type: "string", name: "formules_eyebrow", label: "Formules — sur-titre" },
          { type: "string", name: "formules_titre", label: "Formules — titre" },
        ],
      },
      {
        name: "page_quintessence",
        label: "Page Quintessence",
        path: "src/content/pages",
        format: "md",
        match: { include: "quintessence" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "string", name: "hero_lead", label: "Accroche" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "image", name: "silence_image", label: "Photo — Le silence" },
          { type: "image", name: "crea_image", label: "Photo — La creativite" },
          { type: "image", name: "resp_image", label: "Respiration (fond)" },
          { type: "image", name: "fin_image", label: "Fond de fin" },
          { type: "string", name: "passage", label: "Passage", ui: { component: "textarea" } },
          { type: "string", name: "citation", label: "Citation", description: "*mot* = manuscrite" },
          { type: "string", name: "silence_titre", label: "Silence — titre" },
          { type: "string", name: "silence_texte", label: "Silence — texte", ui: { component: "textarea" } },
          { type: "string", name: "crea_titre", label: "Creativite — titre" },
          { type: "string", name: "crea_texte", label: "Creativite — texte", ui: { component: "textarea" } },
          { type: "string", name: "pratiques_eyebrow", label: "Pratiques — sur-titre" },
          { type: "string", name: "pratiques_titre", label: "Pratiques — titre" },
          { type: "string", name: "pratiques", label: "Pratiques (liste)", list: true },
          { type: "string", name: "cta_texte", label: "Phrase de fin" },
        ],
      },
      {
        name: "page_contact",
        label: "Page Contact",
        path: "src/content/pages",
        format: "md",
        match: { include: "contact" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "string", name: "intro", label: "Introduction", ui: { component: "textarea" } },
          { type: "string", name: "appel_eyebrow", label: "Appel — sur-titre" },
          { type: "string", name: "appel_texte", label: "Appel — texte", ui: { component: "textarea" } },
          { type: "string", name: "appel_cta", label: "Appel — bouton" },
        ],
      },
      {
        name: "page_agenda",
        label: "Page Agenda",
        path: "src/content/pages",
        format: "md",
        match: { include: "agenda" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
        ],
      },
      {
        name: "page_partenaires",
        label: "Page Partenaires",
        path: "src/content/pages",
        format: "md",
        match: { include: "partenaires" },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: "string", name: "hero_eyebrow", label: "Sur-titre" },
          { type: "string", name: "hero_titre", label: "Titre" },
          { type: "image", name: "hero_image", label: "Fond du hero" },
          { type: "object", name: "partenaires", label: "Partenaires", list: true,
            ui: { itemProps: (i) => ({ label: i && i.n ? i.n : "Partenaire" }) },
            fields: [
              { type: "string", name: "n", label: "Nom" },
              { type: "string", name: "d", label: "Description" },
              { type: "string", name: "lien", label: "Lien" },
              { type: "image", name: "logo", label: "Logo" },
              { type: "boolean", name: "logoWhite", label: "Logo a mettre en blanc" },
              { type: "image", name: "image", label: "Photo (fond de carte)" },
            ] },
        ],
      },
    ],
  },
});

// redeploy 18:59 — schema register (branche par defaut = tina)
