import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const videVersUndefined = (v: unknown) => (v === '' || v === null ? undefined : v);

const agenda = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/agenda' }),
  schema: z.object({
    titre: z.string(),
    categorie: z.enum(['soin', 'atelier', 'retraite', 'immersion', 'voyage-sonore', 'accompagnement', 'cercle', 'residence']),
    date: z.preprocess(videVersUndefined, z.coerce.date().optional()),
    date_fin: z.preprocess(videVersUndefined, z.coerce.date().optional()),
    lieu: z.string().optional(),
    prix: z.string().optional(),
    rythme: z.string().optional(),
    heure: z.string().optional(),
    earlybird: z.string().optional(),
    cta: z.string().optional(),
    site: z.string().optional(),
    resume: z.string().optional(),
    image: z.string().optional(),
    lien: z.string().optional(),
    reservable: z.boolean().default(false),
    ordre: z.number().default(0),
    publie: z.boolean().default(true),
  }),
});

const offres = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/offres' }),
  schema: z.object({
    titre: z.string(),
    categorie: z.enum(['soin', 'accompagnement']),
    image: z.string().optional(),
    prix: z.string().optional(),
    duree: z.string().optional(),
    format: z.string().optional(),
    tag: z.string().optional(),
    resume: z.string().optional(),
    tarifs: z.array(z.object({ label: z.string(), prix: z.string(), detail: z.string().optional() })).optional(),
    lien: z.string().optional(),
    reservable: z.boolean().default(true),
    ordre: z.number().default(0),
    publie: z.boolean().default(true),
  }),
});

const pages = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/pages' }),
  schema: z.object({
    hero_eyebrow: z.string().optional(),
    hero_titre: z.string().optional(),
    hero_accent: z.string().optional(),
    hero_paragraphe: z.string().optional(),
    hero_cta: z.string().optional(),
    piliers_titre: z.string().optional(),
    citation1: z.string().optional(),
    propositions_titre: z.string().optional(),
    propositions: z.array(z.object({ titre: z.string(), texte: z.string(), cta: z.string().optional(), image: z.string().optional() })).optional(),
    citation2: z.string().optional(),
    citation_contact: z.string().optional(),
    form_titre: z.string().optional(),
    form_intro: z.string().optional(),
    parcours_titre: z.string().optional(),
    parcours_texte: z.string().optional(),
    parcours_cta: z.string().optional(),
    piliers_eyebrow: z.string().optional(),
    agenda_eyebrow: z.string().optional(),
    art_eyebrow: z.string().optional(),
    art_titre: z.string().optional(),
    temoins_eyebrow: z.string().optional(),
    partenaires_eyebrow: z.string().optional(),
    form_eyebrow: z.string().optional(),
    appel_eyebrow: z.string().optional(),
    appel_texte: z.string().optional(),
    appel_cta: z.string().optional(),
    temoins: z.array(z.object({ t: z.string(), n: z.string(), c: z.string().optional() })).optional(),
    chapitres: z.array(z.object({ titre: z.string(), texte: z.string(), image: z.string().optional() })).optional(),
    coeur: z.string().optional(),
    soins_eyebrow: z.string().optional(),
    soins_titre: z.string().optional(),
    soins_intro: z.string().optional(),
    hero_image: z.string().optional(),
    portrait_image: z.string().optional(),
    resp1_image: z.string().optional(),
    resp2_image: z.string().optional(),
    resp3_image: z.string().optional(),
    art1_image: z.string().optional(),
    art2_image: z.string().optional(),
    art3_image: z.string().optional(),
    art4_image: z.string().optional(),
    outils_image: z.string().optional(),
    silence_image: z.string().optional(),
    crea_image: z.string().optional(),
    resp_image: z.string().optional(),
    fin_image: z.string().optional(),
    hero_lead: z.string().optional(),
    intro: z.string().optional(),
    passage: z.string().optional(),
    citation: z.string().optional(),
    pourqui_eyebrow: z.string().optional(),
    pourqui_titre: z.string().optional(),
    pourqui_texte: z.string().optional(),
    outils_eyebrow: z.string().optional(),
    outils_titre: z.string().optional(),
    outils: z.array(z.string()).optional(),
    formules_eyebrow: z.string().optional(),
    formules_titre: z.string().optional(),
    silence_titre: z.string().optional(),
    silence_texte: z.string().optional(),
    crea_titre: z.string().optional(),
    crea_texte: z.string().optional(),
    pratiques_eyebrow: z.string().optional(),
    pratiques_titre: z.string().optional(),
    pratiques: z.array(z.string()).optional(),
    cta_texte: z.string().optional(),
    partenaires: z.array(z.object({ n: z.string(), d: z.string().optional(), lien: z.string().optional(), logo: z.string().optional(), logoWhite: z.boolean().optional(), image: z.string().optional() })).optional(),
  }),
});

export const collections = { agenda, offres, pages };
